name: torch-env
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.7
  - pytorch=1.8
  - numpy
  - git
  - pip
  - pip:
    - setuptools_scm
    - twine
    - wheel
    - dunamai
